### PR TITLE
DCC 4781 dictionary viewer feature update

### PR DESCRIPTION
**Pull request by SidSyrus**
Changes mentioned in #11 and JSHint error fix.

### CODE REVIEW

**Comment by SidSyrus** [comment]
test this please

**Comment by SidSyrus** [comment]
ok to test

**Comment by SidSyrus** [comment]
test this please

**Comment by btiernay** [comment]
test this please

**Comment by btiernay** [comment]
ok to test

**Comment by btiernay** [comment]
Built on https://dcc-jenkins.oicr.on.ca/view/PR%20Builds/job/dcc-submission-pr/70/

**Pull request merged**
